-- MySQL Script generated by MySQL Workbench
-- Tue Oct 13 22:24:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lush
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lush
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lush` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `lush` ;

-- -----------------------------------------------------
-- Table `lush`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`image` (
  `image__id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image__image` MEDIUMBLOB NOT NULL,
  `image__deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`image__id`),
  UNIQUE INDEX `images__id_UNIQUE` (`image__id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`audio` (
  `audio__id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `audio__audio` LONGBLOB NOT NULL,
  `audio__title` VARCHAR(255) NULL,
  `audio__deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`audio__id`),
  UNIQUE INDEX `audio__id_UNIQUE` (`audio__id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`artist` (
  `artist__id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `artist__name` VARCHAR(255) NULL,
  `artist__description` VARCHAR(10240) NULL,
  `artist__deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`artist__id`),
  UNIQUE INDEX `artist__id_UNIQUE` (`artist__id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`post` (
  `post__id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post__date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `post__deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`post__id`),
  UNIQUE INDEX `post__id_UNIQUE` (`post__id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`post_audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`post_audio` (
  `post_audio__post__id` INT UNSIGNED NOT NULL,
  `post_audio__audio__id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_audio__post__id`, `post_audio__audio__id`),
  CONSTRAINT `post_audio__post__id`
    FOREIGN KEY (`post_audio__post__id`)
    REFERENCES `lush`.`post` (`post__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_audio__audio__id`
    FOREIGN KEY (`post_audio__audio__id`)
    REFERENCES `lush`.`audio` (`audio__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`tag` (
  `tag__id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag__name` VARCHAR(255) NOT NULL,
  `tag__deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`tag__id`),
  UNIQUE INDEX `tag__id_UNIQUE` (`tag__id` ASC) VISIBLE,
  UNIQUE INDEX `tag__name_UNIQUE` (`tag__name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`post_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`post_image` (
  `post_image__post__id` INT UNSIGNED NOT NULL,
  `post_image__image__id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_image__post__id`, `post_image__image__id`),
  INDEX `post_image__image__id_idx` (`post_image__image__id` ASC) VISIBLE,
  CONSTRAINT `post_image__post__id`
    FOREIGN KEY (`post_image__post__id`)
    REFERENCES `lush`.`post` (`post__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_image__image__id`
    FOREIGN KEY (`post_image__image__id`)
    REFERENCES `lush`.`image` (`image__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`post_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`post_tag` (
  `post_tag__audio__id` INT UNSIGNED NOT NULL,
  `post_tag__tag__id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_tag__audio__id`, `post_tag__tag__id`),
  INDEX `post_tag__tag__id_idx` (`post_tag__tag__id` ASC) VISIBLE,
  CONSTRAINT `post_tag__audio__id`
    FOREIGN KEY (`post_tag__audio__id`)
    REFERENCES `lush`.`audio` (`audio__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_tag__tag__id`
    FOREIGN KEY (`post_tag__tag__id`)
    REFERENCES `lush`.`tag` (`tag__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`audio_artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`audio_artist` (
  `audio_artist__audio__id` INT UNSIGNED NOT NULL,
  `audio_artist__artist__id` INT UNSIGNED NOT NULL,
  `audio_artist__artist__position` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`audio_artist__audio__id`, `audio_artist__artist__id`),
  CONSTRAINT `audio_artist__artist__id`
    FOREIGN KEY (`audio_artist__artist__id`)
    REFERENCES `lush`.`artist` (`artist__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `audio_artist__audio__id`
    FOREIGN KEY (`audio_artist__audio__id`)
    REFERENCES `lush`.`audio` (`audio__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`image_artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`image_artist` (
  `image_artist__image__id` INT UNSIGNED NOT NULL,
  `image_artist__artist__id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`image_artist__image__id`, `image_artist__artist__id`),
  INDEX `image_artist__artist__id_idx` (`image_artist__artist__id` ASC) VISIBLE,
  CONSTRAINT `image_artist__image__id`
    FOREIGN KEY (`image_artist__image__id`)
    REFERENCES `lush`.`image` (`image__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `image_artist__artist__id`
    FOREIGN KEY (`image_artist__artist__id`)
    REFERENCES `lush`.`artist` (`artist__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`artist_in_filename`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`artist_in_filename` (
  `artist_in_filename__id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `artist_in_filename__name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`artist_in_filename__id`),
  UNIQUE INDEX `artist_in_filename__name_UNIQUE` (`artist_in_filename__name` ASC) VISIBLE,
  UNIQUE INDEX `artist_in_filename__id_UNIQUE` (`artist_in_filename__id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`artist_in_filename_artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`artist_in_filename_artist` (
  `artist_in_filename_artist__artist_in_filename__id` INT UNSIGNED NOT NULL,
  `artist_in_filename_artist__artist__id` INT UNSIGNED NOT NULL,
  `artist_in_filename_artist__artist_position` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`artist_in_filename_artist__artist_in_filename__id`, `artist_in_filename_artist__artist__id`),
  CONSTRAINT `artist_artist_in_filename__artist__id`
    FOREIGN KEY (`artist_in_filename_artist__artist__id`)
    REFERENCES `lush`.`artist` (`artist__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artist_in_filename_artist__artist_in_filename__id`
    FOREIGN KEY (`artist_in_filename_artist__artist_in_filename__id`)
    REFERENCES `lush`.`artist_in_filename` (`artist_in_filename__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lush`.`audio_filename`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lush`.`audio_filename` (
  `audio_filename__name` VARCHAR(255) NOT NULL,
  `audio_filename__renamed_title` VARCHAR(255) NOT NULL,
  `audio_filename__artist_in_filename__id` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `audio_filename__name_UNIQUE` (`audio_filename__name` ASC) VISIBLE,
  PRIMARY KEY (`audio_filename__name`),
  INDEX `audio_filename__artist_in_filename_idx` (`audio_filename__artist_in_filename__id` ASC) VISIBLE,
  CONSTRAINT `audio_filename__artist_in_filename`
    FOREIGN KEY (`audio_filename__artist_in_filename__id`)
    REFERENCES `lush`.`artist_in_filename` (`artist_in_filename__id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
